### PR TITLE
fixed issue 40

### PR DESCRIPTION
**Pull request by milanych**
Also sorted some lint error

### CODE REVIEW

**Comment by milanych** [comment]
Hi! Any comments, any additions?

**Comment by Codeshark-NET** [comment]
Thanks for the PR and Sorry @milanych , I still need to test it, will get on it soon 👍

**Review by Codeshark-NET — CHANGES_REQUESTED** [review]
Thanks again for the PR @milanych! 🙌

I found 2 things to be fixed:

1. The "project age" sorting is not sorting correctly, see below where I added the datestamp of repository.created_at. 
2. It's a bit strange that "Recent issues" doesn't follow the same sorting functionality as the other sorting-buttons. I think it should be the same (with ascending and descending), alongside the other code

image

**Comment by Ly0n** [comment]
Any progress here? @milanych @Codeshark-NET

**Comment by milanych** [comment]
Hi! I am on the vacation till April.

Kind regards,
*Vadim Zotov*

Sheffield, United Kingdom
☎ +44 7880 805656
✉ ***@***.***

**Comment by milanych** [comment]
Now it's sorted, I guess

**Comment by Codeshark-NET** [comment]
> Now it's sorted, I guess

Pun-intended, eh? Nice one! 😉

I just added a commit to your branch, cleaning up a bit to make the names accurately reflect what they do now. When testing it does seem to sort correctly on my end, yes. 👍

Thanks again @milanych and hope you had a good vacation too. 🙏

**Pull request merged**
